### ISSUE TITLE
V11 Issue Tracker

### ISSUE THREAD

**Issue by LebombJames** [foundryvtt-starfinder/foundryvtt-starfinder#1034]
- [x] Localisations need to be migrated to the new `TYPES.Actor/Item` format
- [x] Initialisation of the rules engine throws an error at startup, everything works as expected, but moving it to the `init` hook solves the issue
- [x] Templates silently fail to draw. They throw a deprecation warning but fixing that changes nothing
- [ ] Update the goddamn build pipeline to use the new CLI 😭
