### ISSUE TITLE
V12 Todo list

### ISSUE THREAD

**Issue by LebombJames** [foundryvtt-starfinder/foundryvtt-starfinder#1291]
- [x] Replace all global scope foundry util function calls with properly namespaced calls. (e.g `duplicate` -> `foundry.utils.duplicate`
- [x] Defer to new core measurement tools
- [x] Replace references of roll term classes to properly namespaced calls
- [x] Unfuck synchronous roll evaluations (async rolls 🥳)
  - [x] Partially: `DiceSFRPG.simplifyRollFormula` returns `NaN` for paranthetical terms.
- [ ] Migrate from `select` to `selectOptions` in Handlebars files.
- [x] Change path for global canvas lumionsity in `vision.js`
    - Still to do: update vision modes with new features for Darkness, luminosity etc.
- [x] Change path for default actor model in `tokendocument.js`
- [x] Update `_preUpdate`s to account for the whole document being present, not just the diff
    - Seemed to work as is? Strange
- [x] Migrate or patch roll parser to account for unbracketed functions preceding dice (`floor()d6`)
- [x] Condition/effect Icons are not appearing on tokens
- [x] Token Condition Hud is missing condition names

**Comment by BroderPeters** [comment]
Are the two remaining ones already worked on and can I support or try to implement them myself? (haven't worked on the project before)

**Comment by ian612** [comment]
`selectOptions` was added in #1401, so I'm going to close this out as completed.
