### ISSUE TITLE
SF Enhanced Checklist

### ISSUE THREAD

**Issue by Iankid** [foundryvtt-starfinder/foundryvtt-starfinder#1294]
This checklist if to show what is in the pull requests already, and what still remains to be worked on.
If an item is marked WIP, it can still be worked on. Look for the draft PR for it to see what has been made for it.
There are also many new rules presented in here. I'll add checks for the ones I note. But please make mention if you see any missing from this list.

- [x] Species
- [x] Class Features
- [x] Feats
- [x] Enhanced Classes
- [x] Themes
- [x] Archetypes
- [x] Spells
- [x] Rituals (Edit existing Journal Compendium, making sure to mark book source)
- [x] Creature Companions
- [x] Scaling Equipment Rules
- [x] Augmentations (can be subdivided)
- [x] Magic Items
- [x] Technological Items
- [x] Hybrid Items
- [x] Grenades
- [x] Serums
- [x] Personal Items
- [x] Narrative Starship Combat rules
- [x] GM Tools
- [x] Resolve Points (Can be added alongside the existing Resolve Points rules, as it's own pages)

**Comment by ian612** [comment]
Before tech/magic/hybrid items are entered, this issue (https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/issues/1220) needs to be resolved, which means PR https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/pull/1108 should be merged first.

**Comment by ian612** [comment]
Links to the relevant in progress PRs:
- https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/pull/1273
- https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/pull/1274
- https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/pull/1276
- https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/pull/1277
- https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/pull/1279

**Comment by ilya-vasiuk** [comment]
Just to mark as WIP
- #1371

**Comment by rmorgens** [comment]
#1408 Adds the various equipment types

**Comment by rmorgens** [comment]
#1409  Adds the Enhanced Resolve Point usages to the SFRPG Rules compendium

**Comment by ian612** [comment]
I'm going to move tracking of this to [here](https://github.com/orgs/foundryvtt-starfinder/projects/3/views/2), as a status board seems more appropriate. I'll leave this issue open until we're finished, though.

**Comment by rmorgens** [comment]
#1408 Covers the equipment (Augmentations, Magic, Tech, Hybrid, Serums, Grenades, Personal items)
